# This workflow will install dependencies, build app, lint files and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build, lint and test application
run-name: ${{ github.actor }} is building, linting and testing application
on:
  pull_request:
    branches: [ $default-branch ]
  push:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up java version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: |
          ./mvnw --batch-mode dependency:go-offline

      - name: Build application
        run: |
          ./mvnw --batch-mode -DskipTests clean package

      - name: Lint application files
        uses: vroy/gha-kotlin-linter@v1

      - name: Test application
        run: |
          ./mvnw --batch-mode clean verify
