name: Test component - Poetry
run-name: ${{ github.event_name }} by ${{ github.actor }} - Test component - Poetry
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'hotfix/**'

jobs:
  test-component-poetry:
    uses: gouv-nc/github-ci-lib-yaml/.github/workflows/callable-poetry-test-component.yml@v2.0.0
    secrets: inherit
