name: Prepare for production - Yarn trinity
run-name: ${{ github.event_name }} by ${{ github.actor }} - Prepare for production - Yarn trinity
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare-for-production-yarn-trinity:
    uses: gouv-nc/github-ci-lib-yaml/.github/workflows/callable-yarn-trinity-prepare-for-production.yml@v2.0.0
    secrets: inherit
    with:
      git_tag: ${{ github.ref_name }}
