name: Increment RC version - Yarn lib
run-name: ${{ github.event_name }} by ${{ github.actor }}
on:
  push:
    branches:
      - 'main'

jobs:
  increment-rc-version-yarn-lib:
    uses: gouv-nc/github-ci-lib-yaml/.github/workflows/callable-yarn-lib-increment-rc-version.yml@v2.0.0
    secrets: inherit
